// Copyright (c) 2023 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=6b6a7f754abc9ee5d6f775ba9eee802d3244faf5$
//

#ifndef HONEYCOMB_INCLUDE_CAPI_HONEYCOMB_SCHEME_CAPI_H_
#define HONEYCOMB_INCLUDE_CAPI_HONEYCOMB_SCHEME_CAPI_H_
#pragma once

#include "include/capi/honey_base_capi.h"
#include "include/capi/honey_browser_capi.h"
#include "include/capi/honey_frame_capi.h"
#include "include/capi/honey_request_capi.h"
#include "include/capi/honey_resource_handler_capi.h"
#include "include/capi/honey_response_capi.h"

#ifdef __cplusplus
extern "C" {
#endif

struct _honey_scheme_handler_factory_t;

///
/// Structure that manages custom scheme registrations.
///
typedef struct _honey_scheme_registrar_t {
  ///
  /// Base structure.
  ///
  honey_base_scoped_t base;

  ///
  /// Register a custom scheme. This function should not be called for the
  /// built-in HTTP, HTTPS, FILE, FTP, ABOUT and DATA schemes.
  ///
  /// See honey_scheme_options_t for possible values for |options|.
  ///
  /// This function may be called on any thread. It should only be called once
  /// per unique |scheme_name| value. If |scheme_name| is already registered or
  /// if an error occurs this function will return false (0).
  ///
  int(HONEYCOMB_CALLBACK* add_custom_scheme)(struct _honey_scheme_registrar_t* self,
                                       const honey_string_t* scheme_name,
                                       int options);
} honey_scheme_registrar_t;

///
/// Structure that creates honey_resource_handler_t instances for handling scheme
/// requests. The functions of this structure will always be called on the IO
/// thread.
///
typedef struct _honey_scheme_handler_factory_t {
  ///
  /// Base structure.
  ///
  honey_base_ref_counted_t base;

  ///
  /// Return a new resource handler instance to handle the request or an NULL
  /// reference to allow default handling of the request. |browser| and |frame|
  /// will be the browser window and frame respectively that originated the
  /// request or NULL if the request did not originate from a browser window
  /// (for example, if the request came from honey_urlrequest_t). The |request|
  /// object passed to this function cannot be modified.
  ///
  struct _honey_resource_handler_t*(HONEYCOMB_CALLBACK* create)(
      struct _honey_scheme_handler_factory_t* self,
      struct _honey_browser_t* browser,
      struct _honey_frame_t* frame,
      const honey_string_t* scheme_name,
      struct _honey_request_t* request);
} honey_scheme_handler_factory_t;

///
/// Register a scheme handler factory with the global request context. An NULL
/// |domain_name| value for a standard scheme will cause the factory to match
/// all domain names. The |domain_name| value will be ignored for non-standard
/// schemes. If |scheme_name| is a built-in scheme and no handler is returned by
/// |factory| then the built-in scheme handler factory will be called. If
/// |scheme_name| is a custom scheme then you must also implement the
/// honey_app_t::on_register_custom_schemes() function in all processes. This
/// function may be called multiple times to change or remove the factory that
/// matches the specified |scheme_name| and optional |domain_name|. Returns
/// false (0) if an error occurs. This function may be called on any thread in
/// the browser process. Using this function is equivalent to calling honey_reques
/// t_context_t::honey_request_context_get_global_context()->register_scheme_handl
/// er_factory().
///
HONEYCOMB_EXPORT int honey_register_scheme_handler_factory(
    const honey_string_t* scheme_name,
    const honey_string_t* domain_name,
    honey_scheme_handler_factory_t* factory);

///
/// Clear all scheme handler factories registered with the global request
/// context. Returns false (0) on error. This function may be called on any
/// thread in the browser process. Using this function is equivalent to calling
/// honey_request_context_t::honey_request_context_get_global_context()->clear_schem
/// e_handler_factories().
///
HONEYCOMB_EXPORT int honey_clear_scheme_handler_factories(void);

#ifdef __cplusplus
}
#endif

#endif  // HONEYCOMB_INCLUDE_CAPI_HONEYCOMB_SCHEME_CAPI_H_
