// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=bb4f6bacea8366b11d1526059c5ad4c3df495630$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_LIST_VALUE_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_LIST_VALUE_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/honey_values_capi.h"
#include "include/honey_values.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombListValueCppToC : public HoneycombCppToCRefCounted<HoneycombListValueCppToC,
                                                      HoneycombListValue,
                                                      honey_list_value_t> {
 public:
  HoneycombListValueCppToC();
  virtual ~HoneycombListValueCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_LIST_VALUE_CPPTOC_H_
