// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=5e9c671740881e345231547607160ce167d37728$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_PDF_PRINT_CALLBACK_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_PDF_PRINT_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_HONEYCOMB_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/honey_browser_capi.h"
#include "include/capi/honey_client_capi.h"
#include "include/honey_browser.h"
#include "include/honey_client.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class HoneycombPdfPrintCallbackCppToC
    : public HoneycombCppToCRefCounted<HoneycombPdfPrintCallbackCppToC,
                                 HoneycombPdfPrintCallback,
                                 honey_pdf_print_callback_t> {
 public:
  HoneycombPdfPrintCallbackCppToC();
  virtual ~HoneycombPdfPrintCallbackCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_PDF_PRINT_CALLBACK_CPPTOC_H_
