// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a0cdfb84f8b30f01dd01556ad3e1725e043641e0$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_RENDER_HANDLER_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_RENDER_HANDLER_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_HONEYCOMB_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/honey_render_handler_capi.h"
#include "include/honey_render_handler.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class HoneycombRenderHandlerCppToC
    : public HoneycombCppToCRefCounted<HoneycombRenderHandlerCppToC,
                                 HoneycombRenderHandler,
                                 honey_render_handler_t> {
 public:
  HoneycombRenderHandlerCppToC();
  virtual ~HoneycombRenderHandlerCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_RENDER_HANDLER_CPPTOC_H_
