// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f5efbaafb5a54dfb9deb422cf31a0908c8a4cfc3$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_RESOURCE_READ_CALLBACK_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_RESOURCE_READ_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/honey_resource_handler_capi.h"
#include "include/honey_resource_handler.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombResourceReadCallbackCppToC
    : public HoneycombCppToCRefCounted<HoneycombResourceReadCallbackCppToC,
                                 HoneycombResourceReadCallback,
                                 honey_resource_read_callback_t> {
 public:
  HoneycombResourceReadCallbackCppToC();
  virtual ~HoneycombResourceReadCallbackCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_RESOURCE_READ_CALLBACK_CPPTOC_H_
