// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=da417f77c868bf40de0bff713b6eb935ffb845ea$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_SHARED_PROCESS_MESSAGE_BUILDER_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_SHARED_PROCESS_MESSAGE_BUILDER_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/honey_shared_process_message_builder_capi.h"
#include "include/honey_shared_process_message_builder.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombSharedProcessMessageBuilderCppToC
    : public HoneycombCppToCRefCounted<HoneycombSharedProcessMessageBuilderCppToC,
                                 HoneycombSharedProcessMessageBuilder,
                                 honey_shared_process_message_builder_t> {
 public:
  HoneycombSharedProcessMessageBuilderCppToC();
  virtual ~HoneycombSharedProcessMessageBuilderCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_SHARED_PROCESS_MESSAGE_BUILDER_CPPTOC_H_
