// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=684bc72317e634d7357bdea53bf7dfe81d9d536b$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_THREAD_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_THREAD_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/honey_thread_capi.h"
#include "include/honey_thread.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombThreadCppToC
    : public HoneycombCppToCRefCounted<HoneycombThreadCppToC, HoneycombThread, honey_thread_t> {
 public:
  HoneycombThreadCppToC();
  virtual ~HoneycombThreadCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_THREAD_CPPTOC_H_
