// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=048b61ed29f9db56cba1a55354c367f941a59b14$
//

#include "libhoney_dll/ctocpp/menu_model_ctocpp.h"
#include "libhoney_dll/cpptoc/menu_model_delegate_cpptoc.h"
#include "libhoney_dll/shutdown_checker.h"

// STATIC METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombMenuModel> HoneycombMenuModel::CreateMenuModel(
    HoneycombRefPtr<HoneycombMenuModelDelegate> delegate) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: delegate; type: refptr_diff
  DCHECK(delegate.get());
  if (!delegate.get()) {
    return nullptr;
  }

  // Execute
  honey_menu_model_t* _retval =
      honey_menu_model_create(HoneycombMenuModelDelegateCppToC::Wrap(delegate));

  // Return type: refptr_same
  return HoneycombMenuModelCToCpp::Wrap(_retval);
}

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::IsSubMenu() {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_sub_menu)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_sub_menu(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::Clear() {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, clear)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->clear(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") size_t HoneycombMenuModelCToCpp::GetCount() {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_count)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  size_t _retval = _struct->get_count(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::AddSeparator() {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, add_separator)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->add_separator(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::AddItem(int command_id, const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, add_item)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval = _struct->add_item(_struct, command_id, label.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::AddCheckItem(int command_id, const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, add_check_item)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval = _struct->add_check_item(_struct, command_id, label.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::AddRadioItem(int command_id,
                                      const HoneycombString& label,
                                      int group_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, add_radio_item)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval =
      _struct->add_radio_item(_struct, command_id, label.GetStruct(), group_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombMenuModel> HoneycombMenuModelCToCpp::AddSubMenu(int command_id,
                                                       const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, add_sub_menu)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return nullptr;
  }

  // Execute
  honey_menu_model_t* _retval =
      _struct->add_sub_menu(_struct, command_id, label.GetStruct());

  // Return type: refptr_same
  return HoneycombMenuModelCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::InsertSeparatorAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, insert_separator_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->insert_separator_at(_struct, index);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::InsertItemAt(size_t index,
                                      int command_id,
                                      const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, insert_item_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval =
      _struct->insert_item_at(_struct, index, command_id, label.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::InsertCheckItemAt(size_t index,
                                           int command_id,
                                           const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, insert_check_item_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval = _struct->insert_check_item_at(_struct, index, command_id,
                                              label.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::InsertRadioItemAt(size_t index,
                                           int command_id,
                                           const HoneycombString& label,
                                           int group_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, insert_radio_item_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval = _struct->insert_radio_item_at(_struct, index, command_id,
                                              label.GetStruct(), group_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombMenuModel> HoneycombMenuModelCToCpp::InsertSubMenuAt(
    size_t index,
    int command_id,
    const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, insert_sub_menu_at)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return nullptr;
  }

  // Execute
  honey_menu_model_t* _retval = _struct->insert_sub_menu_at(
      _struct, index, command_id, label.GetStruct());

  // Return type: refptr_same
  return HoneycombMenuModelCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::Remove(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, remove)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->remove(_struct, command_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::RemoveAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, remove_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->remove_at(_struct, index);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") int HoneycombMenuModelCToCpp::GetIndexOf(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_index_of)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_index_of(_struct, command_id);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") int HoneycombMenuModelCToCpp::GetCommandIdAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_command_id_at)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_command_id_at(_struct, index);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetCommandIdAt(size_t index, int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_command_id_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_command_id_at(_struct, index, command_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
HoneycombString HoneycombMenuModelCToCpp::GetLabel(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_label)) {
    return HoneycombString();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_string_userfree_t _retval = _struct->get_label(_struct, command_id);

  // Return type: string
  HoneycombString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

NO_SANITIZE("cfi-icall")
HoneycombString HoneycombMenuModelCToCpp::GetLabelAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_label_at)) {
    return HoneycombString();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_string_userfree_t _retval = _struct->get_label_at(_struct, index);

  // Return type: string
  HoneycombString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetLabel(int command_id, const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_label)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval = _struct->set_label(_struct, command_id, label.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetLabelAt(size_t index, const HoneycombString& label) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_label_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: label; type: string_byref_const
  DCHECK(!label.empty());
  if (label.empty()) {
    return false;
  }

  // Execute
  int _retval = _struct->set_label_at(_struct, index, label.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
HoneycombMenuModel::MenuItemType HoneycombMenuModelCToCpp::GetType(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_type)) {
    return MENUITEMTYPE_NONE;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_menu_item_type_t _retval = _struct->get_type(_struct, command_id);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
HoneycombMenuModel::MenuItemType HoneycombMenuModelCToCpp::GetTypeAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_type_at)) {
    return MENUITEMTYPE_NONE;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_menu_item_type_t _retval = _struct->get_type_at(_struct, index);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") int HoneycombMenuModelCToCpp::GetGroupId(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_group_id)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_group_id(_struct, command_id);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") int HoneycombMenuModelCToCpp::GetGroupIdAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_group_id_at)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_group_id_at(_struct, index);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetGroupId(int command_id, int group_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_group_id)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_group_id(_struct, command_id, group_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetGroupIdAt(size_t index, int group_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_group_id_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_group_id_at(_struct, index, group_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombMenuModel> HoneycombMenuModelCToCpp::GetSubMenu(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_sub_menu)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_menu_model_t* _retval = _struct->get_sub_menu(_struct, command_id);

  // Return type: refptr_same
  return HoneycombMenuModelCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombMenuModel> HoneycombMenuModelCToCpp::GetSubMenuAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_sub_menu_at)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_menu_model_t* _retval = _struct->get_sub_menu_at(_struct, index);

  // Return type: refptr_same
  return HoneycombMenuModelCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::IsVisible(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_visible)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_visible(_struct, command_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::IsVisibleAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_visible_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_visible_at(_struct, index);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetVisible(int command_id, bool visible) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_visible)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_visible(_struct, command_id, visible);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetVisibleAt(size_t index, bool visible) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_visible_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_visible_at(_struct, index, visible);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::IsEnabled(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_enabled)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_enabled(_struct, command_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::IsEnabledAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_enabled_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_enabled_at(_struct, index);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetEnabled(int command_id, bool enabled) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_enabled)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_enabled(_struct, command_id, enabled);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetEnabledAt(size_t index, bool enabled) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_enabled_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_enabled_at(_struct, index, enabled);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::IsChecked(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_checked)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_checked(_struct, command_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombMenuModelCToCpp::IsCheckedAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_checked_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_checked_at(_struct, index);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetChecked(int command_id, bool checked) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_checked)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_checked(_struct, command_id, checked);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetCheckedAt(size_t index, bool checked) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_checked_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_checked_at(_struct, index, checked);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::HasAccelerator(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, has_accelerator)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->has_accelerator(_struct, command_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::HasAcceleratorAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, has_accelerator_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->has_accelerator_at(_struct, index);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetAccelerator(int command_id,
                                        int key_code,
                                        bool shift_pressed,
                                        bool ctrl_pressed,
                                        bool alt_pressed) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_accelerator)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_accelerator(
      _struct, command_id, key_code, shift_pressed, ctrl_pressed, alt_pressed);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetAcceleratorAt(size_t index,
                                          int key_code,
                                          bool shift_pressed,
                                          bool ctrl_pressed,
                                          bool alt_pressed) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_accelerator_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_accelerator_at(
      _struct, index, key_code, shift_pressed, ctrl_pressed, alt_pressed);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::RemoveAccelerator(int command_id) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, remove_accelerator)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->remove_accelerator(_struct, command_id);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::RemoveAcceleratorAt(size_t index) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, remove_accelerator_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->remove_accelerator_at(_struct, index);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::GetAccelerator(int command_id,
                                        int& key_code,
                                        bool& shift_pressed,
                                        bool& ctrl_pressed,
                                        bool& alt_pressed) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_accelerator)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: shift_pressed; type: bool_byref
  int shift_pressedInt = shift_pressed;
  // Translate param: ctrl_pressed; type: bool_byref
  int ctrl_pressedInt = ctrl_pressed;
  // Translate param: alt_pressed; type: bool_byref
  int alt_pressedInt = alt_pressed;

  // Execute
  int _retval = _struct->get_accelerator(_struct, command_id, &key_code,
                                         &shift_pressedInt, &ctrl_pressedInt,
                                         &alt_pressedInt);

  // Restore param:shift_pressed; type: bool_byref
  shift_pressed = shift_pressedInt ? true : false;
  // Restore param:ctrl_pressed; type: bool_byref
  ctrl_pressed = ctrl_pressedInt ? true : false;
  // Restore param:alt_pressed; type: bool_byref
  alt_pressed = alt_pressedInt ? true : false;

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::GetAcceleratorAt(size_t index,
                                          int& key_code,
                                          bool& shift_pressed,
                                          bool& ctrl_pressed,
                                          bool& alt_pressed) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_accelerator_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Translate param: shift_pressed; type: bool_byref
  int shift_pressedInt = shift_pressed;
  // Translate param: ctrl_pressed; type: bool_byref
  int ctrl_pressedInt = ctrl_pressed;
  // Translate param: alt_pressed; type: bool_byref
  int alt_pressedInt = alt_pressed;

  // Execute
  int _retval =
      _struct->get_accelerator_at(_struct, index, &key_code, &shift_pressedInt,
                                  &ctrl_pressedInt, &alt_pressedInt);

  // Restore param:shift_pressed; type: bool_byref
  shift_pressed = shift_pressedInt ? true : false;
  // Restore param:ctrl_pressed; type: bool_byref
  ctrl_pressed = ctrl_pressedInt ? true : false;
  // Restore param:alt_pressed; type: bool_byref
  alt_pressed = alt_pressedInt ? true : false;

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetColor(int command_id,
                                  honey_menu_color_type_t color_type,
                                  honey_color_t color) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_color)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_color(_struct, command_id, color_type, color);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetColorAt(int index,
                                    honey_menu_color_type_t color_type,
                                    honey_color_t color) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_color_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->set_color_at(_struct, index, color_type, color);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::GetColor(int command_id,
                                  honey_menu_color_type_t color_type,
                                  honey_color_t& color) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_color)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_color(_struct, command_id, color_type, &color);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::GetColorAt(int index,
                                    honey_menu_color_type_t color_type,
                                    honey_color_t& color) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_color_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_color_at(_struct, index, color_type, &color);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetFontList(int command_id,
                                     const HoneycombString& font_list) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_font_list)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: font_list

  // Execute
  int _retval =
      _struct->set_font_list(_struct, command_id, font_list.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombMenuModelCToCpp::SetFontListAt(int index, const HoneycombString& font_list) {
  shutdown_checker::AssertNotShutdown();

  honey_menu_model_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_font_list_at)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: font_list

  // Execute
  int _retval =
      _struct->set_font_list_at(_struct, index, font_list.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

// CONSTRUCTOR - Do not edit by hand.

HoneycombMenuModelCToCpp::HoneycombMenuModelCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

HoneycombMenuModelCToCpp::~HoneycombMenuModelCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
honey_menu_model_t*
HoneycombCToCppRefCounted<HoneycombMenuModelCToCpp, HoneycombMenuModel, honey_menu_model_t>::
    UnwrapDerived(HoneycombWrapperType type, HoneycombMenuModel* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
HoneycombWrapperType HoneycombCToCppRefCounted<HoneycombMenuModelCToCpp,
                                   HoneycombMenuModel,
                                   honey_menu_model_t>::kWrapperType =
    WT_MENU_MODEL;
