// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=fca3fb90b8a74c5cdf3dc16e1489668ce80c7c07$
//

#ifndef HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_DIALOG_HANDLER_CPPTOC_H_
#define HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_DIALOG_HANDLER_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_HONEYCOMB_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/honey_dialog_handler_capi.h"
#include "include/honey_dialog_handler.h"
#include "libhoneycomb_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class HoneycombDialogHandlerCppToC
    : public HoneycombCppToCRefCounted<HoneycombDialogHandlerCppToC,
                                 HoneycombDialogHandler,
                                 honey_dialog_handler_t> {
 public:
  HoneycombDialogHandlerCppToC();
  virtual ~HoneycombDialogHandlerCppToC();
};

#endif  // HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_DIALOG_HANDLER_CPPTOC_H_
