// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=81dc12ded9752671497f775c397ca120632c4ddb$
//

#ifndef HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_END_TRACING_CALLBACK_CPPTOC_H_
#define HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_END_TRACING_CALLBACK_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_HONEYCOMB_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/honey_trace_capi.h"
#include "include/honey_trace.h"
#include "libhoneycomb_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class HoneycombEndTracingCallbackCppToC
    : public HoneycombCppToCRefCounted<HoneycombEndTracingCallbackCppToC,
                                 HoneycombEndTracingCallback,
                                 honey_end_tracing_callback_t> {
 public:
  HoneycombEndTracingCallbackCppToC();
  virtual ~HoneycombEndTracingCallbackCppToC();
};

#endif  // HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_END_TRACING_CALLBACK_CPPTOC_H_
