// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=fd8c0866622e63f6564c0b00107ebcb0c82d60fe$
//

#ifndef HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_FIND_HANDLER_CPPTOC_H_
#define HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_FIND_HANDLER_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_HONEYCOMB_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/honey_find_handler_capi.h"
#include "include/honey_find_handler.h"
#include "libhoneycomb_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class HoneycombFindHandlerCppToC : public HoneycombCppToCRefCounted<HoneycombFindHandlerCppToC,
                                                        HoneycombFindHandler,
                                                        honey_find_handler_t> {
 public:
  HoneycombFindHandlerCppToC();
  virtual ~HoneycombFindHandlerCppToC();
};

#endif  // HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_FIND_HANDLER_CPPTOC_H_
