// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=9b393780a7f736211be3b2ac604af8b59226db5e$
//

#ifndef HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_MEDIA_ROUTER_CPPTOC_H_
#define HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_MEDIA_ROUTER_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/honey_media_router_capi.h"
#include "include/honey_media_router.h"
#include "libhoneycomb_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombMediaRouterCppToC : public HoneycombCppToCRefCounted<HoneycombMediaRouterCppToC,
                                                        HoneycombMediaRouter,
                                                        honey_media_router_t> {
 public:
  HoneycombMediaRouterCppToC();
  virtual ~HoneycombMediaRouterCppToC();
};

#endif  // HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_MEDIA_ROUTER_CPPTOC_H_
