// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=1305b95acf584a0a0e5fd412e948f195233f476b$
//

#ifndef HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_XML_READER_CPPTOC_H_
#define HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_XML_READER_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/honey_xml_reader_capi.h"
#include "include/honey_xml_reader.h"
#include "libhoneycomb_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombXmlReaderCppToC : public HoneycombCppToCRefCounted<HoneycombXmlReaderCppToC,
                                                      HoneycombXmlReader,
                                                      honey_xml_reader_t> {
 public:
  HoneycombXmlReaderCppToC();
  virtual ~HoneycombXmlReaderCppToC();
};

#endif  // HONEYCOMB_LIBHONEYCOMB_DLL_CPPTOC_XML_READER_CPPTOC_H_
