// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=5d7f30f1265294fc8617b444bd35bee3da172746$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_VIEWS_MENU_BUTTON_PRESSED_LOCK_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_VIEWS_MENU_BUTTON_PRESSED_LOCK_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/views/honey_menu_button_capi.h"
#include "include/capi/views/honey_menu_button_delegate_capi.h"
#include "include/views/honey_menu_button.h"
#include "include/views/honey_menu_button_delegate.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombMenuButtonPressedLockCppToC
    : public HoneycombCppToCRefCounted<HoneycombMenuButtonPressedLockCppToC,
                                 HoneycombMenuButtonPressedLock,
                                 honey_menu_button_pressed_lock_t> {
 public:
  HoneycombMenuButtonPressedLockCppToC();
  virtual ~HoneycombMenuButtonPressedLockCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_VIEWS_MENU_BUTTON_PRESSED_LOCK_CPPTOC_H_
