// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=13140a32b465eaf52f13693cd244a9b47eda5068$
//

#ifndef HONEYCOMB_LIBHONEYCOMB_DLL_CTOCPP_VIEWS_BUTTON_DELEGATE_CTOCPP_H_
#define HONEYCOMB_LIBHONEYCOMB_DLL_CTOCPP_VIEWS_BUTTON_DELEGATE_CTOCPP_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/views/honey_button_capi.h"
#include "include/capi/views/honey_button_delegate_capi.h"
#include "include/views/honey_button.h"
#include "include/views/honey_button_delegate.h"
#include "libhoneycomb_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class HoneycombButtonDelegateCToCpp
    : public HoneycombCToCppRefCounted<HoneycombButtonDelegateCToCpp,
                                 HoneycombButtonDelegate,
                                 honey_button_delegate_t> {
 public:
  HoneycombButtonDelegateCToCpp();
  virtual ~HoneycombButtonDelegateCToCpp();

  // HoneycombButtonDelegate methods.
  void OnButtonPressed(HoneycombRefPtr<HoneycombButton> button) override;
  void OnButtonStateChanged(HoneycombRefPtr<HoneycombButton> button) override;

  // HoneycombViewDelegate methods.
  HoneycombSize GetPreferredSize(HoneycombRefPtr<HoneycombView> view) override;
  HoneycombSize GetMinimumSize(HoneycombRefPtr<HoneycombView> view) override;
  HoneycombSize GetMaximumSize(HoneycombRefPtr<HoneycombView> view) override;
  int GetHeightForWidth(HoneycombRefPtr<HoneycombView> view, int width) override;
  void OnParentViewChanged(HoneycombRefPtr<HoneycombView> view,
                           bool added,
                           HoneycombRefPtr<HoneycombView> parent) override;
  void OnChildViewChanged(HoneycombRefPtr<HoneycombView> view,
                          bool added,
                          HoneycombRefPtr<HoneycombView> child) override;
  void OnWindowChanged(HoneycombRefPtr<HoneycombView> view, bool added) override;
  void OnLayoutChanged(HoneycombRefPtr<HoneycombView> view,
                       const HoneycombRect& new_bounds) override;
  void OnFocus(HoneycombRefPtr<HoneycombView> view) override;
  void OnBlur(HoneycombRefPtr<HoneycombView> view) override;
};

#endif  // HONEYCOMB_LIBHONEYCOMB_DLL_CTOCPP_VIEWS_BUTTON_DELEGATE_CTOCPP_H_
