// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=75e19487438e6afe67c650ff5bf616a709c7273b$
//

#include "libhoneycomb_dll/ctocpp/views/menu_button_pressed_lock_ctocpp.h"
#include "libhoneycomb_dll/shutdown_checker.h"

// CONSTRUCTOR - Do not edit by hand.

HoneycombMenuButtonPressedLockCToCpp::HoneycombMenuButtonPressedLockCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

HoneycombMenuButtonPressedLockCToCpp::~HoneycombMenuButtonPressedLockCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
honey_menu_button_pressed_lock_t* HoneycombCToCppRefCounted<
    HoneycombMenuButtonPressedLockCToCpp,
    HoneycombMenuButtonPressedLock,
    honey_menu_button_pressed_lock_t>::UnwrapDerived(HoneycombWrapperType type,
                                                   HoneycombMenuButtonPressedLock*
                                                       c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
HoneycombWrapperType
    HoneycombCToCppRefCounted<HoneycombMenuButtonPressedLockCToCpp,
                        HoneycombMenuButtonPressedLock,
                        honey_menu_button_pressed_lock_t>::kWrapperType =
        WT_MENU_BUTTON_PRESSED_LOCK;
