// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f431a7518ff642f5b307dbd716bfcd75c5bcb37a$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CPPTOC_TEST_TRANSLATOR_TEST_REF_PTR_LIBRARY_CPPTOC_H_
#define HONEYCOMB_LIBHONEY_DLL_CPPTOC_TEST_TRANSLATOR_TEST_REF_PTR_LIBRARY_CPPTOC_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/test/honey_translator_test_capi.h"
#include "include/test/honey_translator_test.h"
#include "libhoney_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class HoneycombTranslatorTestRefPtrLibraryCppToC
    : public HoneycombCppToCRefCounted<HoneycombTranslatorTestRefPtrLibraryCppToC,
                                 HoneycombTranslatorTestRefPtrLibrary,
                                 honey_translator_test_ref_ptr_library_t> {
 public:
  HoneycombTranslatorTestRefPtrLibraryCppToC();
  virtual ~HoneycombTranslatorTestRefPtrLibraryCppToC();
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CPPTOC_TEST_TRANSLATOR_TEST_REF_PTR_LIBRARY_CPPTOC_H_
