// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a30e0b019ab6b34998563c8bf46f7b0c8089c3ba$
//

#ifndef HONEYCOMB_LIBHONEYCOMB_DLL_CTOCPP_SCHEME_REGISTRAR_CTOCPP_H_
#define HONEYCOMB_LIBHONEYCOMB_DLL_CTOCPP_SCHEME_REGISTRAR_CTOCPP_H_
#pragma once

#if !defined(WRAPPING_HONEYCOMB_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/honey_scheme_capi.h"
#include "include/honey_scheme.h"
#include "libhoneycomb_dll/ctocpp/ctocpp_scoped.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class HoneycombSchemeRegistrarCToCpp
    : public HoneycombCToCppScoped<HoneycombSchemeRegistrarCToCpp,
                             HoneycombSchemeRegistrar,
                             honey_scheme_registrar_t> {
 public:
  HoneycombSchemeRegistrarCToCpp();
  virtual ~HoneycombSchemeRegistrarCToCpp();

  // HoneycombSchemeRegistrar methods.
  bool AddCustomScheme(const HoneycombString& scheme_name, int options) override;
};

#endif  // HONEYCOMB_LIBHONEYCOMB_DLL_CTOCPP_SCHEME_REGISTRAR_CTOCPP_H_
