// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=2af462fcea47a649e9f17e4101c37f1f69bba508$
//

#include "libhoneycomb_dll/ctocpp/task_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall") void HoneycombTaskCToCpp::Execute() {
  honey_task_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, execute)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->execute(_struct);
}

// CONSTRUCTOR - Do not edit by hand.

HoneycombTaskCToCpp::HoneycombTaskCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

HoneycombTaskCToCpp::~HoneycombTaskCToCpp() {}

template <>
honey_task_t*
HoneycombCToCppRefCounted<HoneycombTaskCToCpp, HoneycombTask, honey_task_t>::UnwrapDerived(
    HoneycombWrapperType type,
    HoneycombTask* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
HoneycombWrapperType
    HoneycombCToCppRefCounted<HoneycombTaskCToCpp, HoneycombTask, honey_task_t>::kWrapperType =
        WT_TASK;
