// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=d511f3a8273e4d9c6acff3d183b7bfa84e1385e3$
//

#ifndef HONEYCOMB_LIBHONEY_DLL_CTOCPP_TEST_TRANSLATOR_TEST_SCOPED_CLIENT_CTOCPP_H_
#define HONEYCOMB_LIBHONEY_DLL_CTOCPP_TEST_TRANSLATOR_TEST_SCOPED_CLIENT_CTOCPP_H_
#pragma once

#if !defined(BUILDING_HONEYCOMB_SHARED)
#error This file can be included DLL-side only
#endif

#include "include/capi/test/honey_translator_test_capi.h"
#include "include/test/honey_translator_test.h"
#include "libhoney_dll/ctocpp/ctocpp_scoped.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class HoneycombTranslatorTestScopedClientCToCpp
    : public HoneycombCToCppScoped<HoneycombTranslatorTestScopedClientCToCpp,
                             HoneycombTranslatorTestScopedClient,
                             honey_translator_test_scoped_client_t> {
 public:
  HoneycombTranslatorTestScopedClientCToCpp();
  virtual ~HoneycombTranslatorTestScopedClientCToCpp();

  // HoneycombTranslatorTestScopedClient methods.
  int GetValue() override;
};

#endif  // HONEYCOMB_LIBHONEY_DLL_CTOCPP_TEST_TRANSLATOR_TEST_SCOPED_CLIENT_CTOCPP_H_
