// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7fd424327ace29415b68a9c9fb15216e33c7c142$
//

#include "libhoney_dll/ctocpp/test/translator_test_scoped_library_child_ctocpp.h"
#include "libhoney_dll/ctocpp/test/translator_test_scoped_library_child_child_ctocpp.h"

// STATIC METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
HoneycombOwnPtr<HoneycombTranslatorTestScopedLibraryChild>
HoneycombTranslatorTestScopedLibraryChild::Create(int value, int other_value) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_translator_test_scoped_library_child_t* _retval =
      honey_translator_test_scoped_library_child_create(value, other_value);

  // Return type: ownptr_same
  return HoneycombTranslatorTestScopedLibraryChildCToCpp::Wrap(_retval);
}

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
int HoneycombTranslatorTestScopedLibraryChildCToCpp::GetOtherValue() {
  honey_translator_test_scoped_library_child_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_other_value)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_other_value(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void HoneycombTranslatorTestScopedLibraryChildCToCpp::SetOtherValue(int value) {
  honey_translator_test_scoped_library_child_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_other_value)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_other_value(_struct, value);
}

NO_SANITIZE("cfi-icall")
int HoneycombTranslatorTestScopedLibraryChildCToCpp::GetValue() {
  honey_translator_test_scoped_library_t* _struct =
      reinterpret_cast<honey_translator_test_scoped_library_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_value)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_value(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void HoneycombTranslatorTestScopedLibraryChildCToCpp::SetValue(int value) {
  honey_translator_test_scoped_library_t* _struct =
      reinterpret_cast<honey_translator_test_scoped_library_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_value)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_value(_struct, value);
}

// CONSTRUCTOR - Do not edit by hand.

HoneycombTranslatorTestScopedLibraryChildCToCpp::
    HoneycombTranslatorTestScopedLibraryChildCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

HoneycombTranslatorTestScopedLibraryChildCToCpp::
    ~HoneycombTranslatorTestScopedLibraryChildCToCpp() {}

template <>
honey_translator_test_scoped_library_child_t*
HoneycombCToCppScoped<HoneycombTranslatorTestScopedLibraryChildCToCpp,
                HoneycombTranslatorTestScopedLibraryChild,
                honey_translator_test_scoped_library_child_t>::
    UnwrapDerivedOwn(HoneycombWrapperType type,
                     HoneycombOwnPtr<HoneycombTranslatorTestScopedLibraryChild> c) {
  if (type == WT_TRANSLATOR_TEST_SCOPED_LIBRARY_CHILD_CHILD) {
    return reinterpret_cast<honey_translator_test_scoped_library_child_t*>(
        HoneycombTranslatorTestScopedLibraryChildChildCToCpp::UnwrapOwn(
            HoneycombOwnPtr<HoneycombTranslatorTestScopedLibraryChildChild>(
                reinterpret_cast<HoneycombTranslatorTestScopedLibraryChildChild*>(
                    c.release()))));
  }
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
honey_translator_test_scoped_library_child_t*
HoneycombCToCppScoped<HoneycombTranslatorTestScopedLibraryChildCToCpp,
                HoneycombTranslatorTestScopedLibraryChild,
                honey_translator_test_scoped_library_child_t>::
    UnwrapDerivedRaw(HoneycombWrapperType type,
                     HoneycombRawPtr<HoneycombTranslatorTestScopedLibraryChild> c) {
  if (type == WT_TRANSLATOR_TEST_SCOPED_LIBRARY_CHILD_CHILD) {
    return reinterpret_cast<honey_translator_test_scoped_library_child_t*>(
        HoneycombTranslatorTestScopedLibraryChildChildCToCpp::UnwrapRaw(
            HoneycombRawPtr<HoneycombTranslatorTestScopedLibraryChildChild>(
                reinterpret_cast<HoneycombTranslatorTestScopedLibraryChildChild*>(
                    c))));
  }
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
HoneycombWrapperType
    HoneycombCToCppScoped<HoneycombTranslatorTestScopedLibraryChildCToCpp,
                    HoneycombTranslatorTestScopedLibraryChild,
                    honey_translator_test_scoped_library_child_t>::kWrapperType =
        WT_TRANSLATOR_TEST_SCOPED_LIBRARY_CHILD;
