// Copyright (c) 2023 The Honeycomb Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the Honeycomb translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a0b2ffd53a9d1c0054348f323cfdd548cdbeca86$
//

#include "libhoney_dll/ctocpp/views/browser_view_ctocpp.h"
#include "libhoney_dll/cpptoc/client_cpptoc.h"
#include "libhoney_dll/cpptoc/views/browser_view_delegate_cpptoc.h"
#include "libhoney_dll/cpptoc/views/view_delegate_cpptoc.h"
#include "libhoney_dll/ctocpp/browser_ctocpp.h"
#include "libhoney_dll/ctocpp/dictionary_value_ctocpp.h"
#include "libhoney_dll/ctocpp/request_context_ctocpp.h"
#include "libhoney_dll/ctocpp/views/button_ctocpp.h"
#include "libhoney_dll/ctocpp/views/panel_ctocpp.h"
#include "libhoney_dll/ctocpp/views/scroll_view_ctocpp.h"
#include "libhoney_dll/ctocpp/views/textfield_ctocpp.h"
#include "libhoney_dll/ctocpp/views/view_ctocpp.h"
#include "libhoney_dll/ctocpp/views/window_ctocpp.h"
#include "libhoney_dll/shutdown_checker.h"

// STATIC METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombBrowserView> HoneycombBrowserView::CreateBrowserView(
    HoneycombRefPtr<HoneycombClient> client,
    const HoneycombString& url,
    const HoneycombBrowserSettings& settings,
    HoneycombRefPtr<HoneycombDictionaryValue> extra_info,
    HoneycombRefPtr<HoneycombRequestContext> request_context,
    HoneycombRefPtr<HoneycombBrowserViewDelegate> delegate) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: client, url, extra_info, request_context, delegate

  // Execute
  honey_browser_view_t* _retval = honey_browser_view_create(
      HoneycombClientCppToC::Wrap(client), url.GetStruct(), &settings,
      HoneycombDictionaryValueCToCpp::Unwrap(extra_info),
      HoneycombRequestContextCToCpp::Unwrap(request_context),
      HoneycombBrowserViewDelegateCppToC::Wrap(delegate));

  // Return type: refptr_same
  return HoneycombBrowserViewCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombBrowserView> HoneycombBrowserView::GetForBrowser(
    HoneycombRefPtr<HoneycombBrowser> browser) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: browser; type: refptr_same
  DCHECK(browser.get());
  if (!browser.get()) {
    return nullptr;
  }

  // Execute
  honey_browser_view_t* _retval =
      honey_browser_view_get_for_browser(HoneycombBrowserCToCpp::Unwrap(browser));

  // Return type: refptr_same
  return HoneycombBrowserViewCToCpp::Wrap(_retval);
}

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombBrowser> HoneycombBrowserViewCToCpp::GetBrowser() {
  shutdown_checker::AssertNotShutdown();

  honey_browser_view_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_browser)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_browser_t* _retval = _struct->get_browser(_struct);

  // Return type: refptr_same
  return HoneycombBrowserCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombView> HoneycombBrowserViewCToCpp::GetChromeToolbar() {
  shutdown_checker::AssertNotShutdown();

  honey_browser_view_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_chrome_toolbar)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_view_t* _retval = _struct->get_chrome_toolbar(_struct);

  // Return type: refptr_same
  return HoneycombViewCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
void HoneycombBrowserViewCToCpp::SetPreferAccelerators(bool prefer_accelerators) {
  shutdown_checker::AssertNotShutdown();

  honey_browser_view_t* _struct = GetStruct();
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_prefer_accelerators)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_prefer_accelerators(_struct, prefer_accelerators);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombBrowserView> HoneycombBrowserViewCToCpp::AsBrowserView() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, as_browser_view)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_browser_view_t* _retval = _struct->as_browser_view(_struct);

  // Return type: refptr_same
  return HoneycombBrowserViewCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") HoneycombRefPtr<HoneycombButton> HoneycombBrowserViewCToCpp::AsButton() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, as_button)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_button_t* _retval = _struct->as_button(_struct);

  // Return type: refptr_same
  return HoneycombButtonCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") HoneycombRefPtr<HoneycombPanel> HoneycombBrowserViewCToCpp::AsPanel() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, as_panel)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_panel_t* _retval = _struct->as_panel(_struct);

  // Return type: refptr_same
  return HoneycombPanelCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombScrollView> HoneycombBrowserViewCToCpp::AsScrollView() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, as_scroll_view)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_scroll_view_t* _retval = _struct->as_scroll_view(_struct);

  // Return type: refptr_same
  return HoneycombScrollViewCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombTextfield> HoneycombBrowserViewCToCpp::AsTextfield() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, as_textfield)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_textfield_t* _retval = _struct->as_textfield(_struct);

  // Return type: refptr_same
  return HoneycombTextfieldCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") HoneycombString HoneycombBrowserViewCToCpp::GetTypeString() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_type_string)) {
    return HoneycombString();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_string_userfree_t _retval = _struct->get_type_string(_struct);

  // Return type: string
  HoneycombString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

NO_SANITIZE("cfi-icall")
HoneycombString HoneycombBrowserViewCToCpp::ToString(bool include_children) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, to_string)) {
    return HoneycombString();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_string_userfree_t _retval = _struct->to_string(_struct, include_children);

  // Return type: string
  HoneycombString _retvalStr;
  _retvalStr.AttachToUserFree(_retval);
  return _retvalStr;
}

NO_SANITIZE("cfi-icall") bool HoneycombBrowserViewCToCpp::IsValid() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_valid)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_valid(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombBrowserViewCToCpp::IsAttached() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_attached)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_attached(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombBrowserViewCToCpp::IsSame(HoneycombRefPtr<HoneycombView> that) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_same)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: that; type: refptr_same
  DCHECK(that.get());
  if (!that.get()) {
    return false;
  }

  // Execute
  int _retval = _struct->is_same(_struct, HoneycombViewCToCpp::Unwrap(that));

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombViewDelegate> HoneycombBrowserViewCToCpp::GetDelegate() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_delegate)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_view_delegate_t* _retval = _struct->get_delegate(_struct);

  // Return type: refptr_diff
  return HoneycombViewDelegateCppToC::Unwrap(_retval);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombWindow> HoneycombBrowserViewCToCpp::GetWindow() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_window)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_window_t* _retval = _struct->get_window(_struct);

  // Return type: refptr_same
  return HoneycombWindowCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall") int HoneycombBrowserViewCToCpp::GetID() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_id)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_id(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") void HoneycombBrowserViewCToCpp::SetID(int id) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_id)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_id(_struct, id);
}

NO_SANITIZE("cfi-icall") int HoneycombBrowserViewCToCpp::GetGroupID() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_group_id)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_group_id(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") void HoneycombBrowserViewCToCpp::SetGroupID(int group_id) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_group_id)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_group_id(_struct, group_id);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombView> HoneycombBrowserViewCToCpp::GetParentView() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_parent_view)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_view_t* _retval = _struct->get_parent_view(_struct);

  // Return type: refptr_same
  return HoneycombViewCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
HoneycombRefPtr<HoneycombView> HoneycombBrowserViewCToCpp::GetViewForID(int id) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_view_for_id)) {
    return nullptr;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_view_t* _retval = _struct->get_view_for_id(_struct, id);

  // Return type: refptr_same
  return HoneycombViewCToCpp::Wrap(_retval);
}

NO_SANITIZE("cfi-icall")
void HoneycombBrowserViewCToCpp::SetBounds(const HoneycombRect& bounds) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_bounds)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_bounds(_struct, &bounds);
}

NO_SANITIZE("cfi-icall") HoneycombRect HoneycombBrowserViewCToCpp::GetBounds() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_bounds)) {
    return HoneycombRect();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_rect_t _retval = _struct->get_bounds(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") HoneycombRect HoneycombBrowserViewCToCpp::GetBoundsInScreen() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_bounds_in_screen)) {
    return HoneycombRect();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_rect_t _retval = _struct->get_bounds_in_screen(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void HoneycombBrowserViewCToCpp::SetSize(const HoneycombSize& size) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_size)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_size(_struct, &size);
}

NO_SANITIZE("cfi-icall") HoneycombSize HoneycombBrowserViewCToCpp::GetSize() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_size)) {
    return HoneycombSize();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_size_t _retval = _struct->get_size(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void HoneycombBrowserViewCToCpp::SetPosition(const HoneycombPoint& position) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_position)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_position(_struct, &position);
}

NO_SANITIZE("cfi-icall") HoneycombPoint HoneycombBrowserViewCToCpp::GetPosition() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_position)) {
    return HoneycombPoint();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_point_t _retval = _struct->get_position(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
void HoneycombBrowserViewCToCpp::SetInsets(const HoneycombInsets& insets) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_insets)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_insets(_struct, &insets);
}

NO_SANITIZE("cfi-icall") HoneycombInsets HoneycombBrowserViewCToCpp::GetInsets() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_insets)) {
    return HoneycombInsets();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_insets_t _retval = _struct->get_insets(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") HoneycombSize HoneycombBrowserViewCToCpp::GetPreferredSize() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_preferred_size)) {
    return HoneycombSize();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_size_t _retval = _struct->get_preferred_size(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") void HoneycombBrowserViewCToCpp::SizeToPreferredSize() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, size_to_preferred_size)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->size_to_preferred_size(_struct);
}

NO_SANITIZE("cfi-icall") HoneycombSize HoneycombBrowserViewCToCpp::GetMinimumSize() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_minimum_size)) {
    return HoneycombSize();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_size_t _retval = _struct->get_minimum_size(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") HoneycombSize HoneycombBrowserViewCToCpp::GetMaximumSize() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_maximum_size)) {
    return HoneycombSize();
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_size_t _retval = _struct->get_maximum_size(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
int HoneycombBrowserViewCToCpp::GetHeightForWidth(int width) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_height_for_width)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->get_height_for_width(_struct, width);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall") void HoneycombBrowserViewCToCpp::InvalidateLayout() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, invalidate_layout)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->invalidate_layout(_struct);
}

NO_SANITIZE("cfi-icall") void HoneycombBrowserViewCToCpp::SetVisible(bool visible) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_visible)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_visible(_struct, visible);
}

NO_SANITIZE("cfi-icall") bool HoneycombBrowserViewCToCpp::IsVisible() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_visible)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_visible(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombBrowserViewCToCpp::IsDrawn() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_drawn)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_drawn(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void HoneycombBrowserViewCToCpp::SetEnabled(bool enabled) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_enabled)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_enabled(_struct, enabled);
}

NO_SANITIZE("cfi-icall") bool HoneycombBrowserViewCToCpp::IsEnabled() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_enabled)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_enabled(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
void HoneycombBrowserViewCToCpp::SetFocusable(bool focusable) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_focusable)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_focusable(_struct, focusable);
}

NO_SANITIZE("cfi-icall") bool HoneycombBrowserViewCToCpp::IsFocusable() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_focusable)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_focusable(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") bool HoneycombBrowserViewCToCpp::IsAccessibilityFocusable() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, is_accessibility_focusable)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->is_accessibility_focusable(_struct);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall") void HoneycombBrowserViewCToCpp::RequestFocus() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, request_focus)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->request_focus(_struct);
}

NO_SANITIZE("cfi-icall")
void HoneycombBrowserViewCToCpp::SetBackgroundColor(honey_color_t color) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, set_background_color)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->set_background_color(_struct, color);
}

NO_SANITIZE("cfi-icall")
honey_color_t HoneycombBrowserViewCToCpp::GetBackgroundColor() {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, get_background_color)) {
    return 0;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  honey_color_t _retval = _struct->get_background_color(_struct);

  // Return type: simple
  return _retval;
}

NO_SANITIZE("cfi-icall")
bool HoneycombBrowserViewCToCpp::ConvertPointToScreen(HoneycombPoint& point) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, convert_point_to_screen)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->convert_point_to_screen(_struct, &point);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombBrowserViewCToCpp::ConvertPointFromScreen(HoneycombPoint& point) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, convert_point_from_screen)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->convert_point_from_screen(_struct, &point);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombBrowserViewCToCpp::ConvertPointToWindow(HoneycombPoint& point) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, convert_point_to_window)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->convert_point_to_window(_struct, &point);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombBrowserViewCToCpp::ConvertPointFromWindow(HoneycombPoint& point) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, convert_point_from_window)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  int _retval = _struct->convert_point_from_window(_struct, &point);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombBrowserViewCToCpp::ConvertPointToView(HoneycombRefPtr<HoneycombView> view,
                                              HoneycombPoint& point) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, convert_point_to_view)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: view; type: refptr_same
  DCHECK(view.get());
  if (!view.get()) {
    return false;
  }

  // Execute
  int _retval = _struct->convert_point_to_view(
      _struct, HoneycombViewCToCpp::Unwrap(view), &point);

  // Return type: bool
  return _retval ? true : false;
}

NO_SANITIZE("cfi-icall")
bool HoneycombBrowserViewCToCpp::ConvertPointFromView(HoneycombRefPtr<HoneycombView> view,
                                                HoneycombPoint& point) {
  shutdown_checker::AssertNotShutdown();

  honey_view_t* _struct = reinterpret_cast<honey_view_t*>(GetStruct());
  if (HONEYCOMB_MEMBER_MISSING(_struct, convert_point_from_view)) {
    return false;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: view; type: refptr_same
  DCHECK(view.get());
  if (!view.get()) {
    return false;
  }

  // Execute
  int _retval = _struct->convert_point_from_view(
      _struct, HoneycombViewCToCpp::Unwrap(view), &point);

  // Return type: bool
  return _retval ? true : false;
}

// CONSTRUCTOR - Do not edit by hand.

HoneycombBrowserViewCToCpp::HoneycombBrowserViewCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

HoneycombBrowserViewCToCpp::~HoneycombBrowserViewCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
honey_browser_view_t*
HoneycombCToCppRefCounted<HoneycombBrowserViewCToCpp, HoneycombBrowserView, honey_browser_view_t>::
    UnwrapDerived(HoneycombWrapperType type, HoneycombBrowserView* c) {
  DCHECK(false) << "Unexpected class type: " << type;
  return nullptr;
}

template <>
HoneycombWrapperType HoneycombCToCppRefCounted<HoneycombBrowserViewCToCpp,
                                   HoneycombBrowserView,
                                   honey_browser_view_t>::kWrapperType =
    WT_BROWSER_VIEW;
